### ISSUE TITLE
Unable to sniff packets in real-time.

### ISSUE THREAD

**Issue by ZPW2002** [hieulw/cicflowmeter#4]
When I use ‘cicflowmeter -i WLAN -u http://localhost:8080/predict’, it sends requests very slowly and is unable to process packets in real-time.
<img width="1280" alt="屏幕截图 2024-05-11 174445" src="https://github.com/hieulw/cicflowmeter/assets/91549832/19d0fdc1-71a0-4b56-b21a-e64314a7824f">

**Comment by hieulw** [comment]
The timestamp of the flow is the time when the first packet was captured, not the current timestamp when send the flow.
The flow is sent only when the connection between two nodes (ip:port) is terminated.
- the FIN flag was sent (finish connection)
- no packets is transferred between the two for too long (time-out)

You could add -v for verbose to see how the packet and flow is captures, they're not the same. Realtime packets in its own doesn't make much senses because they don't have any context.
